<?php
/**
 * This file is a part of the CIDRAM package.
 * Homepage: https://cidram.github.io/
 *
 * CIDRAM COPYRIGHT 2016 and beyond by Caleb Mazalevskis (Maikuolan).
 *
 * License: GNU/GPLv2
 * @see LICENSE.txt
 *
 * This file: Extended rules for the search engines blocker module (last modified: 2021.07.02).
 */

/** Prevents execution from outside of CIDRAM. */
if (!defined('CIDRAM')) {
    die('[CIDRAM] This should not be accessed directly.');
}

/** Prevents execution from outside of the CheckFactors closure. */
if (!isset($Factors[$FactorIndex])) {
    die('[CIDRAM] This should not be accessed directly.');
}

/** Safety. */
if (!isset($CIDRAM['RunParamResCache'])) {
    $CIDRAM['RunParamResCache'] = [];
}

/**
 * Define object for these rules for later recall (all parameters inherited from CheckFactors).
 *
 * @param array $Factors All CIDR factors of the IP being checked.
 * @param int $FactorIndex The index of the CIDR factor of the triggered rule.
 * @param string $LN The line information generated by CheckFactors.
 * @param string $Tag The triggered rule's section's name (if there's any).
 */
$CIDRAM['RunParamResCache']['seblocker_rules.php'] = function (array $Factors = [], $FactorIndex = 0, $LN = '', $Tag = '') use (&$CIDRAM) {
    /** Skip further processing if no section tag has been defined. */
    if (!$Tag) {
        return;
    }

    /** Blocks requests from Baidu/百度. */
    if ($Tag === 'SEBlocker/Baidu' && $CIDRAM['Config']['seblocker']['block_baidu']) {
        $CIDRAM['BlockInfo']['ReasonMessage'] = $CIDRAM['Config']['seblocker']['baidu_block_message'];
        if (!empty($CIDRAM['BlockInfo']['WhyReason'])) {
            $CIDRAM['BlockInfo']['WhyReason'] .= ', ';
        }
        $CIDRAM['BlockInfo']['WhyReason'] .= 'Baidu/百度 CIDR' . $LN;
        if (!empty($CIDRAM['BlockInfo']['Signatures'])) {
            $CIDRAM['BlockInfo']['Signatures'] .= ', ';
        }
        $CIDRAM['BlockInfo']['Signatures'] .= $Factors[$FactorIndex];
        $CIDRAM['BlockInfo']['SignatureCount']++;
        return;
    }

    /** Blocks requests from Yandex/Яндекс. */
    if ($Tag === 'SEBlocker/Yandex' && $CIDRAM['Config']['seblocker']['block_yandex']) {
        $CIDRAM['BlockInfo']['ReasonMessage'] = $CIDRAM['Config']['seblocker']['yandex_block_message'];
        if (!empty($CIDRAM['BlockInfo']['WhyReason'])) {
            $CIDRAM['BlockInfo']['WhyReason'] .= ', ';
        }
        $CIDRAM['BlockInfo']['WhyReason'] .= 'Yandex/Яндекс CIDR' . $LN;
        if (!empty($CIDRAM['BlockInfo']['Signatures'])) {
            $CIDRAM['BlockInfo']['Signatures'] .= ', ';
        }
        $CIDRAM['BlockInfo']['Signatures'] .= $Factors[$FactorIndex];
        $CIDRAM['BlockInfo']['SignatureCount']++;
        return;
    }
};

/** Execute object. */
$RunExitCode = $CIDRAM['RunParamResCache']['seblocker_rules.php']($Factors, $FactorIndex, $LN, $Tag);
